### ISSUE TITLE
Add example output

### ISSUE THREAD

**Issue by drasive** [letrunghieu/mysql-workbench-plugin-doc-generating#3]
It would be nice to see an example output generated by this tool without having to run it yourself.

**Comment by letrunghieu** [comment]
Thank for your comment. I added an example output in the [`sakila_output.md`](https://github.com/letrunghieu/mysql-workbench-plugin-doc-generating/blob/master/sakila_output.md) file. The link is available in the README, too.

**Comment by drasive** [comment]
Thanks, that is really useful.
