### ISSUE TITLE
pip please?

### ISSUE THREAD

**Issue by reggi** [letrunghieu/mysql-workbench-plugin-doc-generating#4]
Please put on pip package manager!

**Comment by letrunghieu** [comment]
You just need one file to run the script. Does it really need to put it on pip?

**Comment by jbelinchonm** [comment]
I didn't even considered the availability in pip. Just downloaded and imported plugin in WB.

Nice job letrunghieu. It was exactly what I was looking for. Thanks a lot.

**Comment by reggi** [comment]
:+1:
