### ISSUE TITLE
Spacing for MarkDown formatting

### ISSUE THREAD

**Issue by L-E-iT** [letrunghieu/mysql-workbench-plugin-doc-generating#9]
Hi,

On lines 16, 31, 33, and 37, I believe there should be spaces after the '#' characters for Markdown text sizing.

on line 47 I believe it is appropriately written.

Example:
```##Test```
##Test

```## Test```
## Test

**Comment by letrunghieu** [comment]
Thank you @L-E-iT , the code is updated.
